<a href="https://colab.research.google.com/github/syket-das/AI-Attendence-Management-System/blob/main/machine_learning_day_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([[1,0,0],[0,1,0],[1,0,1]])
a

array([[1, 0, 0],
       [0, 1, 0],
       [1, 0, 1]])

In [3]:
b = np.array([[1,1,0],[1,2,1],[0,1,2]])
b

array([[1, 1, 0],
       [1, 2, 1],
       [0, 1, 2]])

In [4]:
c = np.matmul(b,a)
c

array([[1, 1, 0],
       [2, 2, 1],
       [2, 1, 2]])

In [5]:
print(a==b)

[[ True False  True]
 [False False False]
 [False False False]]


In [6]:
x = [[2,3,4],[1,2,3],[3,2,1]]

y = [[2,3,4],[1,2,3],[3,2,1]]

In [8]:
sum = [[0,0,0],[0,0,0],[0,0,0]]

print('before',sum)

for i in range(len(x)):
  for j in range(len(y)):
    sum[i][j] = x[i][j] + y[i][j]

sum

before [[0, 0, 0], [0, 0, 0], [0, 0, 0]]


[[4, 6, 8], [2, 4, 6], [6, 4, 2]]